// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(d,h,l,m){function E(){function a(b,c){for(var d,k,t=0,f=c.length;t<f;t++)if(node=c[t],1==node.t){d=F.call(h,node.l);for(var e=0,g=node.a&&node.a.length||0;e<g;e++)k=node.a[e],G.call(d,k.n,k.v);node.c&&a(d,node.c);r.call(b,d)}else 3==node.t&&r.call(b,H.call(h,node.v))}var b=I('[{"t":1,"l":"link","a":[{"n":"rel","v":"stylesheet"},{"n":"type","v":"text/css"},{"n":"href","v":"css/OFUJfr.css"}]},{"t":1,"l":"div","a":[{"n":"class","v":"host"}],"c":[{"t":1,"l":"h1","c":[{"t":3,"v":"Thank You for using Magic Actions"}]},{"t":1,"l":"h3","c":[{"t":3,"v":"Software Made to Make Your Life Better!"}]},{"t":1,"l":"button","a":[{"n":"class","v":"b0"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/home64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Home"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b1"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/opt64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Options"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b2"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/rate64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Rate"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b3"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/contact64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Support"}]}]},{"t":1,"l":"br"}]}]');p=
u&&53<y?u.call(h.body,{mode:"closed"}):h.body;var c=J.call(h);a(c,b);r.call(p,c)}function K(){L.call(M(".b0"));z.call(p,"click",function(a){var b=a.target;if(b=b.className||b.parentElement&&b.parentElement.className||""){if("b0"===b){var c=99;var d=103}else"b1"===b?(c=300,d=200):"b2"===b?(c=101,d=0):"b3"===b&&(c=303,d=103);N(O({id:7,p:c,f:d}));P.call(a);Q.call(a)}},!0)}function M(a){return u&&53<y?R.call(p,a):S.call(h,a)}function a(){}var N=m.sendMessage;m=m.getURL;var A=String.prototype,q=Storage.prototype,
T=Navigator.prototype,U=XMLHttpRequest.prototype,v=DocumentFragment.prototype,c=Document.prototype,B=DOMImplementation.prototype,w=EventTarget.prototype,g=Event.prototype,e=Node.prototype,b=Element.prototype,x=HTMLElement.prototype,F=c.createElement,z=w.addEventListener,J=c.createDocumentFragment,G=b.setAttribute,R=v.querySelector,S=c.querySelector,L=x.focus,r=e.appendChild,H=c.createTextNode,P=g.preventDefault,Q=g.stopPropagation,V=A.slice,C=A.indexOf,u=b.attachShadow||void 0;try{var f=Object.getOwnPropertyDescriptor(Function.prototype,
"apply");f&&(f.configurable=!1,f.writable=!1,Object.defineProperty(Function.prototype,"apply",f))}catch(k){}try{if(f=Object.getOwnPropertyDescriptor(Function.prototype,"call"))f.configurable=!1,f.writable=!1,Object.defineProperty(Function.prototype,"call",f)}catch(k){}q.getItem=a;q.setItem=a;q.removeItem=a;q.clear=a;T.sendBeacon=a;U.open=a;v.querySelector=a;v.querySelectorAll=a;c.createDocumentFragment=a;c.createTextNode=a;c.createElement=a;c.createElementNS=a;c.evaluate=a;c.createEvent=a;c.createCDATASection=
a;c.execCommand=a;c.querySelector=a;c.querySelectorAll=a;c.write=a;c.writeln=a;B.createHTMLDocument=a;B.createDocument=a;w.addEventListener=a;w.removeEventListener=a;g.preventDefault=a;g.stopPropagation=a;g.stopImmediatePropagation=a;e.appendChild=a;e.cloneNode=a;e.getRootNode=a;e.removeChild=a;e.replaceChild=a;e.insertBefore=a;b.attachShadow=a;b.createShadowRoot=a;b.getElementsByClassName=a;b.getElementsByTagName=a;b.getElementsByTagNameNS=a;b.append=a;b.remove=a;b.before=a;b.after=a;b.prepend=a;
b.querySelector=a;b.querySelectorAll=a;b.requestPointerLock=a;b.setAttribute=a;b.removeAttribute=a;b.removeAttributeNS=a;b.removeAttributeNode=a;b.replaceWith=a;b.insertAdjacentElement=a;b.insertAdjacentText=a;b.insertAdjacentHTML=a;x.focus=a;x.click=a;var O=d.JSON.stringify,I=d.JSON.parse,W=d.parseInt,D=l.userAgent,y=function(){var a=C.call(D,"Chrome/");return-1<a?W(V.call(D,a+7)):0}();l=m("YigK.html");var p;0!==C.call(d.location.href,l)&&(d.location.href=l);z.call(d,"DOMContentLoaded",
function(){E();K()},!0)})(window,document,navigator,chrome.runtime);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(d){}try{Object.defineProperty(window,"localStorage",_vd)}catch(d){}try{Object.defineProperty(window,"navigator",_vd)}catch(d){}try{Object.defineProperty(window,"JSON",_vd)}catch(d){}
try{Object.defineProperty(window,"fetch",_vd)}catch(d){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(d){};
