// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(l,O,t,ia,P,u,g,ja,ka,J){function D(b){var c;if((c=la(e))&&0<c.length){c=c[0];var a=e[c];delete e[c];e[c]=a}c=R(e);A="window.msq__='"+c+"'";try{S.call(t,"opt",ma(c))}catch(h){b||w(function(){D(!0)},2E3)}}function T(b){g.query({windowType:"normal",url:"*://*.youtube.com/*",status:"complete"},function(c){for(var a=0,h=c.length;a<h;a++)g.executeScript(c[a].id,{code:b})})}function na(b){U=b;g.query({url:"https://www.mycinema.pro/take-snapshots-of-your-favorite-videos.html"},function(c){c&&c.length?
g.update(c[0].id,{active:!0},function(){g.sendMessage(c[0].id,b)}):g.create({url:"https://www.mycinema.pro/take-snapshots-of-your-favorite-videos.html",active:!0})});w(E,3003)}function V(b){var c,a="https://www.hotcleaner.com/clickclean/install-magic.html https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif/reviews https://www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg?sub_confirmation=1 https://www.facebook.com/magicactions/ https://plus.google.com/110367533603365326399 https://www.youtube.com/watch?list=PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI".split(" "),
h=["vlozXs.html","NOTIFY_HTML_ID.html","iHda.html"],f="options menu cinema support themes volume-control autohd comments contribute 100-top-music-videos news".split(" ");99==b?c="https://www.mycinema.pro/":99<b&&106>b?c=a[b-100]:199<b&&203>b?c=W(h[b-200]):299<b&&311>b&&(c="https://www.mycinema.pro/"+f[b-300]+".html");return c}function F(b,c,a,h){var f={p:b,h:a?!1:!0},e=V(f.p)||"https://www.mycinema.pro/";if(c){f.f=c;var Q=V(c)}void 0!==h&&(f.w=h);Q?oa(function(b){b?(f.a=1,f.u=e):(f.a=
0,f.u=Q);X(f)}):(f.a=2,f.u=e,X(f))}function X(b){var a={url:b.u};void 0!==b.w&&(a.windowId=b.w);g.query(a,function(a){a&&a.length?g.update(a[0].id,{active:!0},function(b){ja.update(b.windowId,{focused:!0})}):(a={url:b.u,active:b.h},void 0!==b.w&&(a.windowId=b.w),g.create(a,function(a){b.t=a.id;w(pa,1500,b)}))})}function pa(b){try{g.get(b.t,function(a){a=a&&a.url||null;a==b.u?x("200 "+B(b.u)):null==a?x("202 "+B(b.u)):x("201 "+B(b.u+"?e="+a))})}catch(c){x("203 "+B(b.u))}}function qa(b,a){7840==b.menuItemId&&
(b="https://www.youtube.com/results?search_query="+B(b.selectionText),0==a.url.indexOf("https://www.youtube.com/")?g.update({url:b}):g.create({url:b,selected:!0}))}function E(){Y("GET","https://clients2.google.com/service/update2/crx?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D7.3.0.7%26uc&_="+ra(),null,0,function(b){})}function oa(b){Y("HEAD","https://www.mycinema.pro/",0,"text",function(a){!a||200!=a.code&&304!=a.code?b():b(1)})}function x(b){b=b||"unk";if(!e.uid){var a=e;var d=y.call(4294967296*
H()>>>0,16);var h=y.call((4294967296*H()&4294922239|16384)>>>0,16),f=y.call((4294967296*H()&3221225471|2147483648)>>>0,16),G=y.call(4294967296*H()>>>0,16);8>d.length&&(d=p.call("0000000"+d,-8));8>h.length&&(h=p.call("0000000"+h,-8));8>f.length&&(f=p.call("0000000"+f,-8));8>G.length&&(G=p.call("0000000"+G,-8));d=sa.call([d,p.call(h,0,4),p.call(h,4),p.call(f,0,4),p.call(f,4)+G],"-");a.uid=d}ta.call(ia,"https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid="+e.uid+"&t=event&ec=app&ea="+
b+"&el=MA 7.3.0.7")}function Y(b,a,e,h,f){var c={code:0},d=new P;ua.call(d,b,a,!0);h&&(d.responseType=h);d.onload=function(b){c.code=this.status||0;c.data=this.response;f(c)};d.onerror=function(){f(c)};d.onabort=function(){f(c)};try{va.call(d,e)}catch(Ba){f(c)}}function ma(b){for(var a="",e=[3,0,0,-3],d,f=0,g=b.length;f<g;f++)d=e[f%4],a=f+d<g?a+y.call(Z.call(b,f+d),16):a+y.call(Z.call(b,f),16);return a}function a(){}var W=u.getURL;O=u.setUninstallURL;var wa=u.onMessage,xa=u.onStartup;u=u.onInstalled;
var C=chrome.Event.prototype.addListener,K=String.prototype,v=Storage.prototype,aa=Navigator.prototype,L=P.prototype,ba=DocumentFragment.prototype,k=Document.prototype,ca=DOMImplementation.prototype,da=EventTarget.prototype,M=Event.prototype,z=Node.prototype,d=Element.prototype,ea=HTMLElement.prototype,ya=v.getItem,S=v.setItem,I=v.removeItem,ta=aa.sendBeacon,ua=L.open,va=L.send,y=Number.prototype.toString,Z=K.charCodeAt,p=K.slice,za=K.match,sa=Array.prototype.join;try{var q=Object.getOwnPropertyDescriptor(Function.prototype,
"apply");q&&(q.configurable=!1,q.writable=!1,Object.defineProperty(Function.prototype,"apply",q))}catch(b){}try{if(q=Object.getOwnPropertyDescriptor(Function.prototype,"call"))q.configurable=!1,q.writable=!1,Object.defineProperty(Function.prototype,"call",q)}catch(b){}v.getItem=a;v.setItem=a;v.removeItem=a;v.clear=a;aa.sendBeacon=a;L.open=a;ba.querySelector=a;ba.querySelectorAll=a;k.createDocumentFragment=a;k.createTextNode=a;k.createElement=a;k.createElementNS=a;k.evaluate=a;k.createEvent=a;k.createCDATASection=
a;k.execCommand=a;k.querySelector=a;k.querySelectorAll=a;k.write=a;k.writeln=a;ca.createHTMLDocument=a;ca.createDocument=a;da.addEventListener=a;da.removeEventListener=a;M.preventDefault=a;M.stopPropagation=a;M.stopImmediatePropagation=a;z.appendChild=a;z.cloneNode=a;z.getRootNode=a;z.removeChild=a;z.replaceChild=a;z.insertBefore=a;d.attachShadow=a;d.createShadowRoot=a;d.getElementsByClassName=a;d.getElementsByTagName=a;d.getElementsByTagNameNS=a;d.append=a;d.remove=a;d.before=a;d.after=a;d.prepend=
a;d.querySelector=a;d.querySelectorAll=a;d.requestPointerLock=a;d.setAttribute=a;d.removeAttribute=a;d.removeAttributeNS=a;d.removeAttributeNode=a;d.replaceWith=a;d.insertAdjacentElement=a;d.insertAdjacentText=a;d.insertAdjacentHTML=a;ea.focus=a;ea.click=a;var R=l.JSON.stringify,N=l.JSON.parse,fa=String.fromCharCode,ha=l.parseInt,ra=Date.now,w=l.setTimeout,B=l.encodeURIComponent,H=Math.random,la=Object.getOwnPropertyNames,r={ver:"7.3.0.7",extURL:"",uid:"",mwvc:!0,color:"yellow",mwvcm:!0,mwvct:!1,
mwvcr:!1,mwvci:1,gap:5,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,anns:!0,cin:!0,cina:!1,cini:1,cinf:!1,cinc:0,cint:0,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,a0:!0,a1:!1,a2:!1,a3:!0,a4:!0,a5:!0,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,mrl:!0},U,e,A;try{O("https://www.mycinema.pro/support.html"),C.call(xa,a)}catch(b){}(function(){a:{var b=ya.call(t,"opt");b="string"===typeof b?b:void 0;if(void 0!==b){if("{"==b.charAt(0))try{b=N(b)}catch(Aa){e=void 0;break a}else try{for(var a=
za.call(b,/.{1,2}/g),d=[3,0,0,-3],h,f="",g=0,l=a.length;g<l;g++)h=d[g%4],f=g+h<l?f+fa(ha(a[g+h],16)):f+fa(ha(a[g],16));b=N(f)}catch(Aa){b=void 0}e=b}else e=void 0}if(void 0===e){e=r;var k=!0}else{for(var m in e)m in r?typeof e[m]!==typeof r[m]&&(e[m]=r[m],k=!0):(delete e[m],k=!0);for(m in r)m in e||(e[m]=r[m],k=!0)}e.ver="7.3.0.7";e.extURL=W("");A="window.msq__='"+R(e)+"'";k&&D()})();C.call(wa,function(b,a,d){if(32===b)return-1<a.tab.index&&g.executeScript(a.tab.id,{code:A,runAt:"document_start"}),
!1;if(0===b)return!1;try{b=N(b)}catch(f){return!1}if(0==b.id)return d({opt:e,url:a.tab.url}),!0;if(2==b.id)"chrome://components/"!=b.url&&"chrome://settings/help"!=b.url||g.create({url:b.url,active:!0});else if(3==b.id){b=b.opt;for(var c in b)c in r&&"ver"!==c&&(e[c]=b[c]);D();T(A)}else if(4==b.id)c=b.name,a=b.ctx,c in r&&"ver"!==c&&(e[c]=b.value,D(),a&&setMenu(e.a0&&e.a3),T(A));else{if(5==b.id)return d({value:e[b.name]}),!0;if(6==b.id)na(b);else if(7==b.id)F(b.p,b.f,b.a);else{if(9==b.id)return d(U),
!0;20==b.id&&x(b.ea)}}return!1});C.call(u,function(a){var b=a&&a.reason||"";"install"===b?(F(99,103,!0),F(100,200),x("installed")):"update"===b&&"7.3.0.7"!==a.previousVersion&&(I.call(t,'""'),I.call(t,"\"'"),I.call(t,"nv"),I.call(t,"7.2.3.3"),S.call(t,"sv",1));w(E,2912)});C.call(ka.onClicked,function(){w(E,3003);F(301,200)});e.a0&&e.a3&&(J.removeAll(),J.create({id:"7840",title:"Search YouTube for %s",contexts:["selection"]}),C.call(J.onClicked,qa));w(E,5007)})(window,document,localStorage,navigator,
XMLHttpRequest,chrome.runtime,chrome.tabs,chrome.windows,chrome.browserAction,chrome.contextMenus);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(l){}try{Object.defineProperty(window,"localStorage",_vd)}catch(l){}try{Object.defineProperty(window,"navigator",_vd)}catch(l){}try{Object.defineProperty(window,"JSON",_vd)}catch(l){}
try{Object.defineProperty(window,"fetch",_vd)}catch(l){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(l){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(l){};
