// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(m,w,ca,T,H,F){function L(c){if(c){var d=c.url;0!=string_indexOf.call(d,"https://www.mycinema.pro/")&&0!=string_indexOf.call(d,da)&&(w.location.href="about:blank");a=c.opt}(c=u)||(c=w.body,c=attachShadowProto&&53<U?attachShadowProto.call(c,{mode:"closed"}):c);u=c;c=createDocumentFragment.call(w);d=k("ul");d.id="opt";x&&(d.className="localPage",w.body.classList.remove("shadow"));appendChild.call(c,d);var f=u,g=k("link");g.rel="stylesheet";g.type="text/css";g.href="css/DOmPr.css";appendChild.call(f,
g);f=createDocumentFragment.call(w);g=k("div");appendChild.call(f,g);var b=createTextNode.call(w,"Hi, our dear friend. Thank you for using Magic Actions! YouTube constantly make changes, and we constantly need to make sure we are in sync. Last years we have been working hard to provide you with the best possible features. ");appendChild.call(g,b);b=k("br");appendChild.call(g,b);b=createTextNode.call(w,"If you feel you have benefited from using the Magic Actions and would like to show your appreciation then you can make a contribution towards our development costs.");
appendChild.call(g,b);b=k("br");appendChild.call(g,b);b=k("button");b.textContent="Support Magic Actions Development …";b.className="IlIv";b.title="Your Donation is Greatly Appreciated!";appendChild.call(g,b);g=k("ul"==d.localName?"li":"div");g.className="msg";appendChild.call(g,f);appendChild.call(d,g);g.style.backgroundImage="none";addEventListener.call(g,"click",ea,!1);l(d,"mwvc",e("o8"),a.mwvc,0,0,x?0:{id:7,p:305,f:0});l(d,"mwvcm",e("o82"),a.mwvcm,1,!a.mwvc);l(d,"mwvct",e("o83"),a.mwvct,1,!a.mwvc);
l(d,"mwvcr",e("o41"),a.mwvcr,1,!a.mwvc);f="red LightPink orange lime GreenYellow yellow gold DodgerBlue aqua magenta DeepPink white".split(" ");g=k("li");b=k("label");g.className="sub";setAttribute.call(g,"disabled",!a.mwvc);g.id="color";b.textContent=e("o9");appendChild.call(g,b);for(var t=0,r=f.length;t<r;t++){var h=f[t];b=k("button");b.id=h;b.style.backgroundColor=h;a.color==h&&(b.className="sel");appendChild.call(g,b);addEventListener.call(b,"click",ha,!1)}appendChild.call(d,g);f=k("li");g=k("label");
f.id="mwvci";f.className="sub";setAttribute.call(f,"disabled",!a.mwvci);g.textContent=e("o23");appendChild.call(f,g);q(f,"vc0",e("o85"),0==a.mwvci,I);q(f,"vc1",e("o24"),1==a.mwvci,I);q(f,"vc2",e("o25"),2==a.mwvci,I);q(f,"vc3",e("o26"),3==a.mwvci,I);appendChild.call(d,f);f=e("o27");g=a.gap;b=!a.mwvc;h=k("li");t=k("label");r=k("input");t.textContent=f;setAttribute.call(t,"for","gap");r.type="range";r.min=1;r.max=25;r.step=1;r.value=g;r.id="gap";r.title="Range: 1-25";appendChild.call(h,t);appendChild.call(h,
r);t=k("span");t.textContent=g;appendChild.call(h,t);h.className="sub";setAttribute.call(h,"disabled",b);appendChild.call(d,h);addEventListener.call(r,"change",ia,!1);l(d,"hq",e("o90"),a.hq,0,0,x?0:{id:7,p:306,f:0});f=k("li");f.id="hqi";f.className="sub";setAttribute.call(f,"disabled",!a.hq);q(f,"highres",e("o91"),"highres"==a.hqi,v);q(f,"hd2880",e("o92"),"hd2880"==a.hqi,v);q(f,"hd2160",e("o93"),"hd2160"==a.hqi,v);q(f,"hd1440",e("o94"),"hd1440"==a.hqi,v);q(f,"hd1080",e("o95"),"hd1080"==a.hqi,v);q(f,
"hd720",e("o96"),"hd720"==a.hqi,v);q(f,"large",e("o97"),"large"==a.hqi,v);q(f,"medium",e("o98"),"medium"==a.hqi,v);q(f,"small",e("o99"),"small"==a.hqi,v);q(f,"tiny",e("o100"),"tiny"==a.hqi,v);appendChild.call(d,f);l(d,"mrl",e("o44"),a.mrl);l(d,"wide",e("o28"),a.wide);l(d,"ww",e("o80"),a.ww);l(d,"cin",e("o29"),a.cin,0,0,x?0:{id:7,p:302,f:0});f=k("li");g=k("label");f.id="cini";f.className="sub";setAttribute.call(f,"disabled",!a.cin);g.textContent=e("o32");appendChild.call(f,g);q(f,"ca0",e("o33"),0==
a.cini,M);q(f,"ca1",e("o34"),1==a.cini,M);q(f,"ca2",e("o35"),2==a.cini,M);appendChild.call(d,f);l(d,"cina",e("o30"),a.cina,1,!a.cin);l(d,"cinf",e("o31"),a.cinf,1,!a.cin);l(d,"pause",e("o17"),a.pause);l(d,"plist",e("o19"),a.plist,1,!a.pause);l(d,"buf",e("o18"),a.buf);l(d,"buf1",e("o63"),a.buf1,1,!a.buf);l(d,"loop",e("o40"),a.loop);l(d,"c0",e("o70"),a.c0,0,0,x?0:{id:7,p:307,f:0});N(d,["c1",e("o71"),a.c1,"c4",e("o86"),a.c4],!a.c0);l(d,"anns",e("o42"),a.anns);l(d,"f0",e("o43"),a.f0);l(d,"h0",e("o50"),
a.h0);N(d,["h7",e("o56"),a.h7,"h1",e("o51"),a.h1,"h2",e("o52"),a.h2,"h3",e("o53"),a.h3,"h4",e("o54"),a.h4],!a.h0);N(d,["h5",e("o55"),a.h5,"h6",e("o64"),a.h6,"h8",e("o57"),a.h8],!a.h0);l(d,"a0",e("o60"),a.a0,0,0,x?0:{id:7,p:304,f:0});l(d,"a4",e("o81"),a.a4,1,!a.a0);l(d,"a1",e("o61"),a.a1,1,!a.a0);l(d,"a2",e("o62"),a.a2,1,!a.a0);l(d,"a3",e("o84"),a.a3,1,!a.a0);l(d,"a5",e("o20"),a.a5,1,!a.a0);f=k("li");g=k("a");f.className="opt";g.textContent="Export Options …";g.className="bttn";addEventListener.call(g,
"click",ja,!1);appendChild.call(f,g);g=k("a");g.textContent="Import Options …";g.className="bttn";addEventListener.call(g,"click",ka,!1);appendChild.call(f,g);appendChild.call(d,f);appendChild.call(u,c);y("#f0").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";c=k("sup");c.textContent=e("m4");c.style.color="red";c.style.verticalAlign="top";appendChild.call(y("#mrl").nextElementSibling,c);y("#mrl").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";
addEventListener.call(m,"message",la,!1);if(O){var p=ma.call(O,"sv")||null;p&&localStorage_removeItem.call(O,"sv")}x||m.top.postMessage(na(z({t:+new Date,i:700,ver:a.ver,sv:p})),"https://www.mycinema.pro")}function la(a){if("https://www.mycinema.pro"===(a.origin||"")&&a.data.constructor===Array)try{var d=a.data;a=[];for(var c=[3,0,0,-3],b,e=0,t=d.length;e<t;e++)b=c[e%4],e+b<t?array_push.call(a,V(d[e+b])):array_push.call(a,V(d[e]));var r=array_join.call(a,"");W(r)}catch(fa){}}function D(a,d,b){E(z({id:4,
name:a,value:d,ctx:b}))}function ha(c){y("#"+a.color).className="";a.color=this.id;this.className="sel";D("color",a.color)}function I(c){y("#vc"+a.mwvci).checked=!1;a.mwvci=G(this.id.charAt(2));this.checked=!0;D("mwvci",a.mwvci)}function M(c){y("#ca"+a.cini).checked=!1;a.cini=G(this.id.charAt(2));this.checked=!0;D("cini",a.cini)}function v(c){y("#"+a.hqi).checked=!1;a.hqi=this.id;this.checked=!0;D("hqi",a.hqi)}function X(c){c=this.id;a[c]=this.checked?!0:!1;D(c,this.checked?!0:!1,"a0"==c||"a3"==c?
!0:!1);c=this.parentElement;if("opt"==c.className)for(c=c.nextElementSibling;c&&("sub"==c.className||"sub multi"==c.className);)setAttribute.call(c,"disabled",!this.checked),c=c.nextElementSibling}function oa(c){a[c.id]=G(c.value);D(c.id,G(c.value))}function ia(a){J&&(pa(J),J=null);this.nextElementSibling.textContent=this.value;J=Y(oa,500,this)}function q(a,d,b,g,e){var c=k("label"),f=k("input");f.type="radio";f.id=d;g&&(f.checked=!0);appendChild.call(a,f);c.textContent=b;setAttribute.call(c,"for",
d);appendChild.call(a,c);addEventListener.call(f,"click",e,!1)}function l(a,d,b,e,h,t,r){var c=k("li"),f=k("label"),g=k("input");f.textContent=b;setAttribute.call(f,"for",d);g.type="checkbox";g.id=d;g.checked=e;appendChild.call(c,g);appendChild.call(c,f);h?(c.className="sub",setAttribute.call(c,"disabled",t)):c.className="opt";r&&(d=k("span"),d.textContent="?",d.title="Learn more about this feature …",d.className="help",Object.defineProperty(d,"mafy",{value:r,writable:!1,configurable:!1,enumerable:!1}),
appendChild.call(c,d),addEventListener.call(d,"click",function(a){E(z(this.mafy))},!1));appendChild.call(a,c);addEventListener.call(g,"click",X,!1)}function N(a,b,f){for(var c=k("li"),d,e,h=0,l=b.length;h<l;h+=3)d=k("label"),e=k("input"),d.textContent=b[h+1],setAttribute.call(d,"for",b[h]),e.type="checkbox",e.id=b[h],e.checked=b[h+2],appendChild.call(c,e),appendChild.call(c,d),addEventListener.call(e,"click",X,!1);c.className="sub multi";setAttribute.call(c,"disabled",f);appendChild.call(a,c)}function ea(a){E(z({id:7,
p:202,f:0}));stopPropagation.call(a)}function ja(){var b=z(a);if(Blob)var d=new Blob([b],{type:"application/json;charset=UTF-8"});else BlobBuilder&&(d=new BlobBuilder,d.append(b),d=d.getBlob("application/json;charset=UTF-8"));qa(d,"MagicActions-Options.json")}function ka(){ra(1E5,function(b){try{b=W(b)}catch(g){return}var d=a.ver,c;for(c in b)void 0!=a[c]&&(a[c]=b[c]);a.ver=d;for(E(z({id:3,opt:a}));u.firstElementChild;)removeChild.call(u,u.firstElementChild);L()})}function ra(a,b){var c=y("#openAs");
c&&removeChild.call(u,c);c=k("input");c.id="openAs";c.style.display="none";c.type="file";appendChild.call(u,c);addEventListener.call(c,"change",function(c){if((c=c.target.files)&&1==c.length&&c[0].size<a){var d=new FileReader;d.onload=function(a){b(a.target.result)};d.readAsText(c[0])}else showMsg("m12",1E3)},!1);el_click.call(c)}function qa(a,b){var c=k("a");c.href=sa(a);setAttribute.call(c,"download",b);el_click.call(c);Y(function(){ta(c.href)},2E3)}function ua(a){va("HEAD","https://www.mycinema.pro/",
0,"text",function(b){!b||200!=b.code&&304!=b.code?a():a(1)})}function va(a,b,e,g,h){var c={code:0},d=new T;xhr_open.call(d,a,b,!0);g&&(d.responseType=g);d.onload=function(a){c.code=this.status||0;c.data=this.response;h(c)};d.onerror=function(){h(c)};d.onabort=function(){h(c)};try{xhr_send.call(d,e)}catch(fa){h(c)}}function na(a){for(var b=[],c=[3,0,0,-3],e,h=0,k=a.length;h<k;h++)e=c[h%4],h+e<k?array_push.call(b,string_charCodeAt.call(a,h+e)):array_push.call(b,string_charCodeAt.call(a,h));return b}
function y(a){return attachShadowProto&&53<U?shadow_querySelector.call(u,a):querySelector.call(w,a)}function k(a){return createElement.call(w,a)}function b(){}var E=H.sendMessage;H=H.getURL;var e=F.getMessage;F=String.prototype;var Z=Array.prototype,C=Storage.prototype,wa=Navigator.prototype,P=T.prototype,Q=DocumentFragment.prototype,p=Document.prototype,aa=DOMImplementation.prototype,R=EventTarget.prototype,K=Event.prototype,A=Node.prototype,h=Element.prototype,S=HTMLElement.prototype;HTMLMediaElement_prototype=
HTMLMediaElement.prototype;var ma=C.getItem;localStorage_setItem=C.setItem;localStorage_removeItem=C.removeItem;createElement=p.createElement;addEventListener=R.addEventListener;createDocumentFragment=p.createDocumentFragment;setAttribute=h.setAttribute;appendChild=A.appendChild;removeChild=A.removeChild;createTextNode=p.createTextNode;stopPropagation=K.stopPropagation;shadow_querySelector=Q.querySelector;querySelector=p.querySelector;array_push=Z.push;array_join=Z.join;string_slice=F.slice;string_charCodeAt=
F.charCodeAt;string_indexOf=F.indexOf;el_click=S.click;xhr_open=P.open;xhr_send=P.send;attachShadowProto=h.attachShadow||void 0;try{var B=Object.getOwnPropertyDescriptor(Function.prototype,"apply");B&&(B.configurable=!1,B.writable=!1,Object.defineProperty(Function.prototype,"apply",B))}catch(c){}try{if(B=Object.getOwnPropertyDescriptor(Function.prototype,"call"))B.configurable=!1,B.writable=!1,Object.defineProperty(Function.prototype,"call",B)}catch(c){}C.getItem=b;C.setItem=b;C.removeItem=b;C.clear=
b;wa.sendBeacon=b;P.open=b;Q.querySelector=b;Q.querySelectorAll=b;p.createDocumentFragment=b;p.createTextNode=b;p.createElement=b;p.createElementNS=b;p.evaluate=b;p.createEvent=b;p.createCDATASection=b;p.execCommand=b;p.querySelector=b;p.querySelectorAll=b;p.write=b;p.writeln=b;aa.createHTMLDocument=b;aa.createDocument=b;R.addEventListener=b;R.removeEventListener=b;K.preventDefault=b;K.stopPropagation=b;K.stopImmediatePropagation=b;A.appendChild=b;A.cloneNode=b;A.getRootNode=b;A.removeChild=b;A.replaceChild=
b;A.insertBefore=b;h.attachShadow=b;h.createShadowRoot=b;h.getElementsByClassName=b;h.getElementsByTagName=b;h.getElementsByTagNameNS=b;h.append=b;h.remove=b;h.before=b;h.after=b;h.prepend=b;h.querySelector=b;h.querySelectorAll=b;h.requestPointerLock=b;h.setAttribute=b;h.removeAttribute=b;h.removeAttributeNS=b;h.removeAttributeNode=b;h.replaceWith=b;h.insertAdjacentElement=b;h.insertAdjacentText=b;h.insertAdjacentHTML=b;S.focus=b;S.click=b;HTMLMediaElement_prototype.play=b;var z=m.JSON.stringify,
W=m.JSON.parse,Y=m.setTimeout,pa=m.clearTimeout,V=String.fromCharCode,G=m.parseInt,ta=m.URL.revokeObjectURL,sa=m.URL.createObjectURL,ba=ca.userAgent,U=function(){var a=string_indexOf.call(ba,"Chrome/");return-1<a?G(string_slice.call(ba,a+7)):0}(),da=H("vlozXs.html"),x=m.self==m.top,u,a,J;try{var O=m.localStorage}catch(c){}addEventListener.call(m,"DOMContentLoaded",function(){x?ua(function(a){a?m.location.href="https://www.mycinema.pro/options.html":E(z({id:0}),L)}):E(z({id:0}),L)},!0)})(window,
document,navigator,XMLHttpRequest,chrome.runtime,chrome.i18n);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(m){}try{Object.defineProperty(window,"localStorage",_vd)}catch(m){}try{Object.defineProperty(window,"navigator",_vd)}catch(m){}try{Object.defineProperty(window,"JSON",_vd)}catch(m){}
try{Object.defineProperty(window,"fetch",_vd)}catch(m){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(m){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(m){};
