// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(e,m,y,l){function F(a,f){var c=q.call(m,f.e);if(!c){(c=q.call(m,f.a))&&0<c.offsetHeight&&c.classList.add(f.b);var b=q.call(m,f.c);b&&(c=G.call(m,"iframe"),f.d?r.call(c,f.d,f.e):c.className=f.e,f.f&&(c.id=f.f),r.call(c,"scrolling","no"),r.call(c,"frameborder","0"),c.src=H(a),I.call(b,c))}}function J(){function a(a){var c=a?a:{w:640,h:350,vid:"pwHX9JT2APQ",lic:"YouTube License",t:"Magic Actions for YouTube™"};c.ver="7.3.0.7";c.ua=1;c.id=12;a=new y;K.call(a,"GET",c.rgba,!0);a.responseType=
"arraybuffer";a.onload=function(a){200==this.status&&(c.rgba=this.response,L(c,"https://www.mycinema.pro"))};M.call(a)}z||(z=!0,N.call(O,a),t(u({id:9}),a))}function P(a){for(var b=[],c=[3,0,0,-3],d,g=0,e=a.length;g<e;g++)d=c[g%4],g+d<e?A.call(b,B(a[g+d])):A.call(b,B(a[g]));return Q.call(b,"")}function a(){}var H=l.getURL,O=l.onMessage,t=l.sendMessage,N=chrome.Event.prototype.addListener;l=Array.prototype;var p=Storage.prototype,R=Navigator.prototype,v=y.prototype,C=DocumentFragment.prototype,d=Document.prototype,
D=DOMImplementation.prototype,w=EventTarget.prototype,x=Event.prototype,k=Node.prototype,b=Element.prototype,E=HTMLElement.prototype,q=d.querySelector,G=d.createElement,I=k.appendChild,r=b.setAttribute,S=w.addEventListener,K=v.open,M=v.send,A=l.push,Q=l.join;try{var h=Object.getOwnPropertyDescriptor(Function.prototype,"apply");h&&(h.configurable=!1,h.writable=!1,Object.defineProperty(Function.prototype,"apply",h))}catch(g){}try{if(h=Object.getOwnPropertyDescriptor(Function.prototype,"call"))h.configurable=
!1,h.writable=!1,Object.defineProperty(Function.prototype,"call",h)}catch(g){}p.getItem=a;p.setItem=a;p.removeItem=a;p.clear=a;R.sendBeacon=a;v.open=a;C.querySelector=a;C.querySelectorAll=a;d.createDocumentFragment=a;d.createTextNode=a;d.createElement=a;d.createElementNS=a;d.evaluate=a;d.createEvent=a;d.createCDATASection=a;d.execCommand=a;d.querySelector=a;d.querySelectorAll=a;d.write=a;d.writeln=a;D.createHTMLDocument=a;D.createDocument=a;w.addEventListener=a;w.removeEventListener=a;x.preventDefault=
a;x.stopPropagation=a;x.stopImmediatePropagation=a;k.appendChild=a;k.cloneNode=a;k.getRootNode=a;k.removeChild=a;k.replaceChild=a;k.insertBefore=a;b.attachShadow=a;b.createShadowRoot=a;b.getElementsByClassName=a;b.getElementsByTagName=a;b.getElementsByTagNameNS=a;b.append=a;b.remove=a;b.before=a;b.after=a;b.prepend=a;b.querySelector=a;b.querySelectorAll=a;b.requestPointerLock=a;b.setAttribute=a;b.removeAttribute=a;b.removeAttributeNS=a;b.removeAttributeNode=a;b.replaceWith=a;b.insertAdjacentElement=
a;b.insertAdjacentText=a;b.insertAdjacentHTML=a;E.focus=a;E.click=a;var u=e.JSON.stringify,T=e.JSON.parse,B=String.fromCharCode,U=Date.now,L=e.postMessage,z;S.call(e,"message",function(a){if("https://www.mycinema.pro"===(a.origin||"")&&a.data.constructor===Array){try{var b=T(P(a.data))}catch(c){b={}}b.t&&(a=U()-b.t,1E3>a&&(a=b.i,2==a?t(u({id:2,url:b.u,incognito:b.p})):300==a?F("vlozXs.html",b):303==a?J():304==a&&t(u({id:0}),function(a){a=a.opt;b.ui&&a.a0&&a.a4&&a.ui&&m.documentElement.classList.add(b.ui)})))}},
!0)})(window,document,XMLHttpRequest,chrome.runtime);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(e){}try{Object.defineProperty(window,"localStorage",_vd)}catch(e){}try{Object.defineProperty(window,"navigator",_vd)}catch(e){}try{Object.defineProperty(window,"JSON",_vd)}catch(e){}
try{Object.defineProperty(window,"fetch",_vd)}catch(e){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(e){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(e){};
